# C Resource System 
# Metafile Template

some/file/that/ is somewhere.txt:
        path: somepath.txt
        creation:
                - echo "Something" > somepath.txt 


somefile.dat:
        path: something.data
        creation:
                - git clone 
                - cd
                - make -j4
                - cp data ../something.data

